### ISSUE TITLE
Pydantic v2

### ISSUE THREAD

**Issue by jplock** [nayaverdier/dyntastic#10]
Support Pydantic v2

**Comment by nayaverdier** [comment]
This is currently blocked by https://github.com/pydantic/pydantic/issues/7586 in order to support `KEYS_ONLY` / `INCLUDE` indexes. Depending on where that ticket goes, I might just leave that feature unimplemented for now when using Pydantic v2 to at least support the majority of the feature set with Pydantic v2.

**Comment by jsjeannotte** [comment]
Hi @nayaverdier ! I was wondering if you've made progress on this? We are down to a handful of dependencies still pinned on v1 (including Dyntastic), and a lot of libraries are already pinned to Pydantic >1. 

Thanks again for the great library, our team is leveraging to build some of our control planes.

**Comment by nayaverdier** [comment]
@jsjeannotte Thanks for the push, I just released `0.13.0a1` which has pydantic v2 support. There were a lot of tricky things to work around, so if you're able to play around with it and make sure it actually works for your use case, that'd be super helpful. If nobody complains, I'll release it in a week or two.

Looking forward to seeing the PR!

**Comment by jsjeannotte** [comment]
@nayaverdier Thanks, will try it today and report back.

**Comment by nayaverdier** [comment]
`0.13.0` is now released, closing this ticket.
